refactor: abstract Raylib keyboard managment
AmozPay/OtterLib pull request #102
Opened 2023-02-11 15:14 UTC by barbo69

We don't need to indicate the type of input and consequently we dont need to rename Keyboard Component to Event Component

2023-02-13 08:44 UTC, lucas-louis approved these changes
LGTM

2023-02-13 13:07 UTC, fzuefo commented on OtterLib/graphic/include/OtterGraphicKeyboard.hpp
> +        enum KeyType {
need to verifie if this not destroy virtuality of the class

2023-02-13 13:12 UTC, fzuefo requested changes
the change are fine to me, but pls solve conflic merge before

2023-02-13 13:13 UTC, fzuefo commented on OtterLib/network/include/NetChannel.hpp
> +// #include "asio.hpp"
not deprecate code but non fonctional part

2023-02-14 13:21 UTC, fzuefo approved these changes

2023-02-14 15:30 UTC, merged